"""Grounded legal answer generation and deterministic verification."""

from .context_builder import RAGContextBuilder
from .generator import (
    FakeLegalAnswerGenerator,
    GeneratedAnswer,
    GeneratedClaim,
    IssueResolution,
    GenerationTelemetry,
    GenerationError,
    GenerationTimeoutError,
    GenerationRequest,
    LegalAnswerGenerator,
    NoOpLegalAnswerGenerator,
    OpenAICompatibleLegalAnswerGenerator,
    OpenAICompatibleSettings,
    InvalidStructuredResponseError,
    ProviderUnavailableError,
    TruncatedGenerationError,
    SupportingQuote,
)
from .issues import (
    ISSUE_PROMPT_VERSION,
    IssueDecompositionError,
    IssueDecompositionRequest,
    IssuePlan,
    OpenAICompatibleIssueDecomposer,
    retrieve_issue_plan,
)
from .context_models import Evidence, PackedContext, TokenBudget, TokenCounter
from .runtime import (
    LLMHealthClient,
    RAGExecutionGate,
    RAGQueueFullError,
    RAGRuntime,
    create_rag_runtime,
)
from .service import GenerationResult, GroundedRAGService, LegalRAGService
from .verifier import (
    GroundingVerifier,
    VerificationCode,
    VerificationIssue,
    VerificationResult,
    VerificationStatus,
    requires_case_specific_prediction_refusal,
)

__all__ = [
    "Evidence",
    "FakeLegalAnswerGenerator",
    "GeneratedAnswer",
    "GeneratedClaim",
    "IssueResolution",
    "GenerationTelemetry",
    "GenerationError",
    "GenerationTimeoutError",
    "GenerationRequest",
    "GenerationResult",
    "GroundedRAGService",
    "GroundingVerifier",
    "LegalAnswerGenerator",
    "InvalidStructuredResponseError",
    "LegalRAGService",
    "NoOpLegalAnswerGenerator",
    "OpenAICompatibleLegalAnswerGenerator",
    "OpenAICompatibleSettings",
    "ProviderUnavailableError",
    "PackedContext",
    "RAGContextBuilder",
    "RAGExecutionGate",
    "RAGQueueFullError",
    "RAGRuntime",
    "LLMHealthClient",
    "TokenBudget",
    "TokenCounter",
    "TruncatedGenerationError",
    "SupportingQuote",
    "ISSUE_PROMPT_VERSION",
    "IssueDecompositionError",
    "IssueDecompositionRequest",
    "IssuePlan",
    "OpenAICompatibleIssueDecomposer",
    "retrieve_issue_plan",
    "VerificationCode",
    "VerificationIssue",
    "VerificationResult",
    "VerificationStatus",
    "create_rag_runtime",
    "requires_case_specific_prediction_refusal",
]
